# Generated by Django 5.0.4 on 2024-08-22 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('otp_code', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_code_datetime_created', models.DateTimeField(auto_now=True)),
                ('complete_info', models.CharField(blank=True, choices=[('cmp', 'Completed'), ('dnt', 'تکمیل نشده'), ('ipr', 'در حال بررسی')], default='n', max_length=10, null=True, verbose_name='Complete Information')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='agent_custom_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='agent_custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='agents.province')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام')),
                ('l_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('sex', models.CharField(blank=True, choices=[('m', 'آقا'), ('f', 'خانم')], max_length=10, null=True, verbose_name='جنسیت')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('fixed_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Fixed Phone Number')),
                ('email', models.CharField(blank=True, max_length=300, null=True, verbose_name='ایمیل')),
                ('national_card', models.ImageField(blank=True, null=True, upload_to='agents/national_card/', verbose_name='تصویر کارت ملی')),
                ('auth_picture', models.ImageField(blank=True, null=True, upload_to='agents/auth_picture/', verbose_name='تصویر احراز هویت')),
                ('bank_card', models.ImageField(blank=True, null=True, upload_to='agents/bank_card/', verbose_name='تصویر کارت بانکی')),
                ('bank_sheba', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bank Sheba')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='نشانی')),
                ('introduction_way', models.CharField(blank=True, choices=[('ins', 'اینستاگرام'), ('y&a', 'Course Videos'), ('ads', 'Advertisements'), ('web', 'Website and Google'), ('frd', 'Friends'), ('oth', 'Others')], max_length=10, null=True, verbose_name='Introduction Way')),
                ('experience', models.CharField(blank=True, choices=[('0', 'No Experience'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('4', '4 years'), ('5-10', '5-10 years'), ('abv10', 'More than 10 years')], max_length=10, null=True, verbose_name='Experience')),
                ('course_tendency', models.CharField(blank=True, choices=[('have', 'Have'), ('dont', 'Have not'), ('seen', 'Have seen')], max_length=10, null=True, verbose_name='Course Tendency')),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='agents.agentcustomusermodel')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='agents.city', verbose_name='شهر')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='agents.province', verbose_name='استان')),
            ],
        ),
    ]
