# Generated by Django 5.0.4 on 2024-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcustomusermodel',
            name='complete_info',
            field=models.CharField(blank=True, choices=[('cmp', 'Completed'), ('dnt', 'تکمیل نشده'), ('ipr', 'در حال بررسی')], default='dnt', max_length=10, null=True, verbose_name='Complete Information'),
        ),
    ]
