# Generated by Django 5.0.4 on 2024-09-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentcustomusermodel_otp_code'),
        ('restates', '0023_tradesession_agent_status_alter_tradesession_status'),
        ('services', '0004_counseling_agent_status_session_agent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=10, null=True, verbose_name='وضعیت پرداخت')),
                ('is_commissioned', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=10, null=True, verbose_name='Commission Status')),
                ('is_requested', models.CharField(blank=True, choices=[('tkn', 'Taken'), ('fre', 'Free'), ('pen', 'در حال بررسی')], default='fre', max_length=10, null=True, verbose_name='Request Status')),
                ('unique_url_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('cns', 'مشاوره'), ('ses', 'نشست'), ('vis', 'بازدید'), ('tds', 'Trade Session')], max_length=6, null=True, verbose_name='Task Type')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_session_agent', to='agents.agentcustomusermodel')),
                ('task_counseling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_task', to='services.counseling')),
                ('task_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_task', to='services.session')),
                ('task_trade_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_session_task', to='restates.tradesession')),
                ('task_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_task', to='services.visit')),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
    ]
