# Generated by Django 5.0.4 on 2024-06-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0002_alter_salefile_unique_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salefile',
            name='unique_url_id',
        ),
    ]
