# Generated by Django 5.0.4 on 2024-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0004_alter_salefile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='salefile',
            name='unique_url_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
