# Generated by Django 5.0.4 on 2024-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0005_salefile_unique_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salefile',
            name='unique_url_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
