# Generated by Django 5.0.4 on 2024-06-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0006_alter_salefile_unique_url_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salefile',
            old_name='file_postal_code',
            new_name='apartment_postal_code',
        ),
    ]
