# Generated by Django 5.0.4 on 2024-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0007_rename_file_postal_code_salefile_apartment_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salefile',
            name='apartment_postal_code',
        ),
        migrations.AddField(
            model_name='salefile',
            name='file_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='File Postal Code'),
        ),
    ]
