# Generated by Django 5.0.4 on 2024-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0008_remove_salefile_apartment_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salefile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='files/covers/', verbose_name='File cover'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover2',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='File cover 2'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover3',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='File cover 3'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover4',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='File cover 4'),
        ),
    ]
