# Generated by Django 5.0.4 on 2024-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0009_alter_salefile_cover_alter_salefile_cover2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salefile',
            name='year',
        ),
        migrations.AddField(
            model_name='salefile',
            name='age',
            field=models.CharField(choices=[('نوساز', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('بیش از 30', 'بیش از 30')], default='1', max_length=15, verbose_name='Year of Construction'),
        ),
    ]
