# Generated by Django 5.0.4 on 2024-07-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0010_remove_salefile_year_salefile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salefile',
            name='age',
            field=models.CharField(choices=[('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='Age of Apartment'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='restates.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='restates.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='file_levels',
            field=models.CharField(blank=True, choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, null=True, verbose_name='File Levels Number'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='level',
            field=models.CharField(choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='restates.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='room',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='Number of Rooms'),
        ),
        migrations.CreateModel(
            name='RentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_deposit', models.PositiveBigIntegerField(verbose_name='Deposit Price')),
                ('price_rent', models.PositiveBigIntegerField(verbose_name='Rent Price')),
                ('convertable', models.CharField(choices=[('is', 'Is'), ('isnt', 'Is not')], max_length=15, verbose_name='Convertable')),
                ('room', models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='Number of Rooms')),
                ('area', models.PositiveIntegerField(verbose_name='Area')),
                ('age', models.CharField(choices=[('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='Age of Apartment')),
                ('document', models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has not')], max_length=15, verbose_name='Document')),
                ('level', models.CharField(choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, verbose_name='سطح')),
                ('parking', models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has not')], max_length=15, verbose_name='Parking')),
                ('elevator', models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has not')], max_length=15, verbose_name='Elevator')),
                ('warehouse', models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has not')], max_length=15, verbose_name='Warehouse')),
                ('cover', models.ImageField(blank=True, upload_to='files/covers/', verbose_name='File cover')),
                ('cover2', models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='File cover 2')),
                ('cover3', models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='File cover 3')),
                ('cover4', models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='File cover 4')),
                ('direction', models.CharField(blank=True, choices=[('nth', 'North'), ('sth', 'South'), ('est', 'East'), ('wst', 'South')], max_length=15, null=True, verbose_name='File Direction')),
                ('file_levels', models.CharField(blank=True, choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, null=True, verbose_name='File Levels Number')),
                ('aparts_per_level', models.CharField(blank=True, choices=[('one', 'تک واحدی'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('more-10', 'بیش از 10')], max_length=15, null=True, verbose_name='Apartments per Level')),
                ('restoration', models.CharField(blank=True, choices=[('done', 'اتمام یافته'), ('dont', 'not Done')], max_length=15, null=True, verbose_name='Restoration')),
                ('bench_stove', models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has not')], max_length=15, null=True, verbose_name='Bench Stove')),
                ('balcony', models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has not')], max_length=15, null=True, verbose_name='Balcony')),
                ('toilet', models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('FG', 'فرنگی'), ('BT', 'هر دو')], max_length=15, null=True, verbose_name='Toilet')),
                ('hot_water', models.CharField(blank=True, choices=[('HW', 'آبگرم\u200cکن'), ('MH', 'موتورخانه'), ('PK', 'پکیج'), ('OT', 'سایر')], max_length=15, null=True, verbose_name='Hot Water System')),
                ('cooling', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cooling System')),
                ('heating', models.CharField(blank=True, max_length=15, null=True, verbose_name='Heating System')),
                ('floor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Floor Type')),
                ('title', models.CharField(max_length=230, verbose_name='File Title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('unique_url_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('acc', 'تایید شده'), ('can', 'رد شده'), ('pen', 'در حال بررسی')], default='pen', max_length=10)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_expired', models.DateTimeField(blank=True, null=True)),
                ('provider_name', models.CharField(max_length=50, verbose_name='Provider Name')),
                ('phone_number_for_contact', models.CharField(blank=True, max_length=11, null=True, verbose_name='Provider Phone Number')),
                ('provider_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Provider National Code')),
                ('owner_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Owner National Code')),
                ('file_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='File Postal Code')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='restates.city', verbose_name='شهر')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='restates.district', verbose_name='District')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='restates.province', verbose_name='استان')),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
    ]
