# Generated by Django 5.0.4 on 2024-07-09 16:33

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0011_alter_salefile_age_alter_salefile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentfile',
            name='age',
            field=models.CharField(choices=[('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='سن آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='aparts_per_level',
            field=models.CharField(blank=True, choices=[('one', 'تک واحدی'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('more-10', 'بیش از 10')], max_length=15, null=True, verbose_name='تعداد واحد در هر طبقه'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='area',
            field=models.PositiveIntegerField(verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='بالکن'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='گاز رومیزی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='convertable',
            field=models.CharField(choices=[('is', 'هست'), ('isnt', 'نیست')], max_length=15, verbose_name='امکان تبدیل ودیعه به اجاره'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='cooling',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم سرمایش'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='files/covers/', verbose_name='تصویر اصلی آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='cover2',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='تصویر دوم آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='cover3',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='تصویر سوم آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='cover4',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='تصویر چهارم آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='direction',
            field=models.CharField(blank=True, choices=[('nth', 'شمالی'), ('sth', 'جنوبی'), ('est', 'شرقی'), ('wst', 'غربی')], max_length=15, null=True, verbose_name='جهت آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='restates.district', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='document',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='سند تک\u200cبرگ'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='elevator',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='file_levels',
            field=models.CharField(blank=True, choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, null=True, verbose_name='تعداد طبقات ساختمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='file_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='floor',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='جنس کف'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='heating',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='hot_water',
            field=models.CharField(blank=True, choices=[('HW', 'آبگرم\u200cکن'), ('MH', 'موتورخانه'), ('PK', 'پکیج'), ('OT', 'سایر')], max_length=15, null=True, verbose_name='سیستم آب گرم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='owner_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی مالک آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='parking',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='phone_number_for_contact',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه منتشر کننده'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='price_deposit',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ ودیعه'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='price_rent',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ اجاره'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='provider_name',
            field=models.CharField(max_length=50, verbose_name='نام منتشر کننده آگهی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='provider_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی منتشر کننده آگهی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='restoration',
            field=models.CharField(blank=True, choices=[('done', 'شده'), ('dont', 'نشده')], max_length=15, null=True, verbose_name='وضعیت بازسازی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='room',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='title',
            field=models.CharField(max_length=230, verbose_name='عنوان آگهی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='toilet',
            field=models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('FG', 'فرنگی'), ('BT', 'هر دو')], max_length=15, null=True, verbose_name='سرویس بهداشتی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='age',
            field=models.CharField(choices=[('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='سن آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='aparts_per_level',
            field=models.CharField(blank=True, choices=[('one', 'تک واحدی'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('more-10', 'بیش از 10')], max_length=15, null=True, verbose_name='تعداد واحد در هر طبقه'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='area',
            field=models.PositiveIntegerField(verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='بالکن'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='گاز رومیزی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cooling',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم سرمایش'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='files/covers/', verbose_name='تصویر اصلی آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover2',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='تصویر دوم آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover3',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='تصویر سوم آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cover4',
            field=models.ImageField(blank=True, null=True, upload_to='files/covers/', verbose_name='تصویر چهارم آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='direction',
            field=models.CharField(blank=True, choices=[('nth', 'شمالی'), ('sth', 'جنوبی'), ('est', 'شرقی'), ('wst', 'غربی')], max_length=15, null=True, verbose_name='جهت آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='restates.district', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='document',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='سند تک\u200cبرگ'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='elevator',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='file_levels',
            field=models.CharField(blank=True, choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, null=True, verbose_name='تعداد طبقات ساختمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='file_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='floor',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='جنس کف'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='heating',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='hot_water',
            field=models.CharField(blank=True, choices=[('HW', 'آبگرم\u200cکن'), ('MH', 'موتورخانه'), ('PK', 'پکیج'), ('OT', 'سایر')], max_length=15, null=True, verbose_name='سیستم آب گرم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='owner_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی مالک آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='parking',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='phone_number_for_contact',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه منتشر کننده'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='provider_name',
            field=models.CharField(max_length=50, verbose_name='نام منتشر کننده آگهی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='provider_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی منتشر کننده آگهی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='restoration',
            field=models.CharField(blank=True, choices=[('done', 'شده'), ('dont', 'نشده')], max_length=15, null=True, verbose_name='وضعیت بازسازی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='room',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='title',
            field=models.CharField(max_length=230, verbose_name='عنوان آگهی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='toilet',
            field=models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('FG', 'فرنگی'), ('BT', 'هر دو')], max_length=15, null=True, verbose_name='سرویس بهداشتی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='انباری'),
        ),
        migrations.CreateModel(
            name='TradeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('thrn', 'تهران'), ('karj', 'کرج'), ('ands', 'Andisheh'), ('shrr', 'Shahriar'), ('prds', 'Pardis'), ('prnd', 'Parand')], default='thrn', max_length=30, verbose_name='شهر')),
                ('location', models.CharField(choices=[('ours', 'Ours'), ('yours', 'Yours')], max_length=30, verbose_name='مکان')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ نشست')),
                ('time', models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان نشست')),
                ('name_and_family_first', models.CharField(max_length=200, verbose_name='First Name and Family')),
                ('name_and_family_second', models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Name and Family')),
                ('phone_number_first', models.CharField(max_length=11, verbose_name='First Phone Number')),
                ('phone_number_second', models.CharField(blank=True, max_length=11, null=True, verbose_name='Second Phone Number')),
                ('trade_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=30, verbose_name='Trade Type')),
                ('ours', models.CharField(choices=[('is', 'هست'), ('isnt', 'Is Not')], max_length=30, verbose_name='Is trade ours?')),
                ('is_success', models.CharField(choices=[('is', 'هست'), ('isnt', 'Is Not')], default='isnt', max_length=200, verbose_name='Is trade successful?')),
                ('is_paid', models.CharField(choices=[('is', 'هست'), ('isnt', 'Is Not')], default='isnt', max_length=200, verbose_name='Is payment done?')),
                ('is_followed', models.CharField(choices=[('is', 'هست'), ('isnt', 'Is Not')], default='isnt', max_length=200, verbose_name='Is trade has follow-up?')),
                ('status', models.CharField(choices=[('acc', 'تایید شده'), ('can', 'رد شده'), ('pen', 'در حال بررسی'), ('done', 'شده')], default='pen', max_length=30, verbose_name='وضعیت')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('rent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='restates.rentfile', verbose_name='Rent File')),
                ('sale_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='restates.salefile', verbose_name='Sale File')),
            ],
        ),
    ]
