# Generated by Django 5.0.4 on 2024-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0012_alter_rentfile_age_alter_rentfile_aparts_per_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentfile',
            name='rent_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salefile',
            name='sale_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tradesession',
            name='trade_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
