# Generated by Django 5.0.4 on 2024-07-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0014_rename_rent_file_code_rentfile_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesession',
            name='rent_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Rent File Code'),
        ),
        migrations.AddField(
            model_name='tradesession',
            name='sale_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Sale File Code'),
        ),
    ]
