# Generated by Django 5.0.4 on 2024-07-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0015_tradesession_rent_code_tradesession_sale_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesession',
            old_name='name_and_family_first',
            new_name='name_and_family',
        ),
        migrations.RenameField(
            model_name='tradesession',
            old_name='phone_number_first',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='tradesession',
            name='name_and_family_second',
        ),
        migrations.RemoveField(
            model_name='tradesession',
            name='phone_number_second',
        ),
    ]
