# Generated by Django 5.0.4 on 2024-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0016_rename_name_and_family_first_tradesession_name_and_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesession',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='First Phone Number'),
        ),
    ]
