# Generated by Django 5.0.4 on 2024-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0019_alter_tradesession_is_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesession',
            name='is_followed',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=200, verbose_name='آیا معامله نیاز به پیگیری دارد؟'),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='is_paid',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=200, verbose_name='آیا پرداخت کمیسیون انجام شده است؟'),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='is_success',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=200, verbose_name='آیا معامله موفقیت\u200cآمیز بود؟'),
        ),
    ]
