# Generated by Django 5.0.4 on 2024-08-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0020_alter_tradesession_is_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentfile',
            name='restoration',
            field=models.CharField(blank=True, choices=[('done', 'انجام\u200cشده'), ('dont', 'نشده')], max_length=15, null=True, verbose_name='وضعیت بازسازی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی')], default='pen', max_length=10),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='restoration',
            field=models.CharField(blank=True, choices=[('done', 'انجام\u200cشده'), ('dont', 'نشده')], max_length=15, null=True, verbose_name='وضعیت بازسازی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی')], default='pen', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی'), ('done', 'انجام\u200cشده')], default='pen', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='نام')),
                ('l_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('sex', models.CharField(choices=[('m', 'آقا'), ('f', 'خانم')], max_length=10, verbose_name='جنسیت')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('fixed_phone', models.CharField(max_length=11, verbose_name='Fixed Phone Number')),
                ('email', models.CharField(max_length=300, unique=True, verbose_name='ایمیل')),
                ('national_card', models.ImageField(blank=True, null=True, upload_to='agents/national_card/', verbose_name='تصویر کارت ملی')),
                ('bank_card', models.ImageField(blank=True, null=True, upload_to='agents/bank_card/', verbose_name='تصویر کارت بانکی')),
                ('auth_picture', models.ImageField(blank=True, null=True, upload_to='agents/auth_picture/', verbose_name='تصویر احراز هویت')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='نشانی')),
                ('introducing', models.CharField(choices=[('ins', 'اینستاگرام'), ('web', 'Website'), ('frn', 'Friends and Relatives'), ('crs', 'Course Videos'), ('ads', 'Advertisements'), ('oth', 'Others')], max_length=10, verbose_name='Introducing Way')),
                ('experience', models.CharField(choices=[('0', 'No Experience'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('5-10', '5-10 years'), ('>10', 'More than 10 years')], max_length=10, verbose_name='Experience')),
                ('course', models.CharField(choices=[('hve', 'Have'), ('dnt', 'Do Not Have'), ('pss', 'Passed')], max_length=10, verbose_name='Introducing Way')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='restates.city', verbose_name='شهر')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='restates.province', verbose_name='استان')),
            ],
        ),
    ]
