# Generated by Django 5.0.4 on 2024-08-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0021_alter_rentfile_restoration_alter_rentfile_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
