# Generated by Django 5.0.4 on 2024-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0022_delete_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesession',
            name='agent_status',
            field=models.CharField(blank=True, choices=[('ass', 'Assigned'), ('wai', 'در انتظار'), ('rej', 'Rejected')], default='wai', max_length=10, null=True, verbose_name='Agent Status'),
        ),
        migrations.AlterField(
            model_name='tradesession',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی'), ('dne', 'انجام\u200cشده')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
    ]
