# Generated by Django 5.0.4 on 2024-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0023_tradesession_agent_status_alter_tradesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesession',
            name='district',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='محله'),
        ),
    ]
