# Generated by Django 5.0.4 on 2024-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0024_tradesession_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesession',
            name='agent_status',
            field=models.CharField(blank=True, choices=[('ass', 'Assigned'), ('wai', 'در انتظار'), ('rej', 'Rejected'), ('fre', 'Free')], default='fre', max_length=10, null=True, verbose_name='Agent Status'),
        ),
    ]
