# Generated by Django 5.0.4 on 2024-09-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0025_alter_tradesession_agent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesession',
            name='agent_status',
        ),
    ]
