# Generated by Django 5.0.4 on 2024-09-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restates', '0026_remove_tradesession_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesession',
            name='status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
