# Generated by Django 5.0.4 on 2024-07-25 10:56

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('maker', models.CharField(max_length=100, verbose_name='Maker')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('district', models.CharField(max_length=50, verbose_name='محله')),
                ('capacity', models.PositiveIntegerField(blank=True, verbose_name='Capacity')),
                ('metric_price', models.PositiveIntegerField(verbose_name='Metric Price')),
                ('buy_assurance', models.BooleanField(default=False, verbose_name='Buy assurance')),
                ('guaranteed_gain', models.BooleanField(default=False, verbose_name='Guaranteed gain')),
                ('guaranteed_gain_percent', models.PositiveIntegerField(verbose_name='Guaranteed gain percent')),
                ('end_time', models.CharField(max_length=200, verbose_name='End time')),
                ('description', django_quill.fields.QuillField(verbose_name='Description')),
                ('status', models.CharField(choices=[('a', 'فعال'), ('s', 'Soon'), ('e', 'Ended')], max_length=10, verbose_name='وضعیت')),
                ('cover', models.ImageField(blank=True, upload_to='cases/covers/', verbose_name='Case Cover')),
                ('cover2', models.ImageField(blank=True, null=True, upload_to='cases/covers/', verbose_name='Case cover 2')),
                ('cover3', models.ImageField(blank=True, null=True, upload_to='cases/covers/', verbose_name='Case cover 3')),
                ('cover4', models.ImageField(blank=True, null=True, upload_to='cases/covers/', verbose_name='Case cover 4')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('unique_url_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='CaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wa', 'Waiting'), ('ca', 'رد شده'), ('do', 'شده')], max_length=10, verbose_name='وضعیت')),
                ('notes', models.CharField(max_length=1000, verbose_name='Notes')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date & time of creation')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Date & time of modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.PositiveIntegerField(default=1, verbose_name='متراژ')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cases.case', verbose_name='Project')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cases.caseorder', verbose_name='Case Order')),
            ],
        ),
    ]
