# Generated by Django 5.0.4 on 2024-07-26 17:12

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=django_quill.fields.QuillField(blank=True, max_length=2000, null=True),
        ),
    ]
