# Generated by Django 5.0.4 on 2024-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='caseorder',
            name='status',
            field=models.CharField(choices=[('wa', 'Waiting'), ('ca', 'رد شده'), ('do', 'شده')], default='wa', max_length=10, verbose_name='وضعیت'),
        ),
    ]
