# Generated by Django 5.0.4 on 2024-07-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_caseorder_notes_alter_caseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseorder',
            name='notes',
        ),
    ]
