# Generated by Django 5.0.4 on 2024-07-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_city_province_district_city_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='case',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.district', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='case',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.province', verbose_name='استان'),
        ),
    ]
