# Generated by Django 5.0.4 on 2024-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_city_alter_case_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseorder',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
