# Generated by Django 5.0.4 on 2024-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counseling',
            name='customer_type',
        ),
        migrations.AlterField(
            model_name='counseling',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('can', 'Canceled'), ('pen', 'Pending'), ('done', 'Done')], default='pen', max_length=30, verbose_name='Status'),
        ),
    ]
