# Generated by Django 5.0.4 on 2024-04-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_counseling_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('can', 'Canceled'), ('pen', 'Pending'), ('done', 'Done')], default='pen', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('can', 'Canceled'), ('pen', 'Pending'), ('done', 'Done')], default='pen', max_length=30, verbose_name='Status'),
        ),
    ]
