# Generated by Django 5.0.4 on 2024-09-05 11:23

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_session_phone_number_alter_session_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling',
            name='agent_status',
            field=models.CharField(blank=True, choices=[('ass', 'Assigned'), ('wai', 'در انتظار'), ('rej', 'Rejected')], default='wai', max_length=10, null=True, verbose_name='Agent Status'),
        ),
        migrations.AddField(
            model_name='session',
            name='agent_status',
            field=models.CharField(blank=True, choices=[('ass', 'Assigned'), ('wai', 'در انتظار'), ('rej', 'Rejected')], default='wai', max_length=10, null=True, verbose_name='Agent Status'),
        ),
        migrations.AddField(
            model_name='visit',
            name='agent_status',
            field=models.CharField(blank=True, choices=[('ass', 'Assigned'), ('wai', 'در انتظار'), ('rej', 'Rejected')], default='wai', max_length=10, null=True, verbose_name='Agent Status'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='counseling_type',
            field=models.CharField(choices=[('ip', 'حضوری'), ('op', 'تلفنی'), ('oc', 'چتی')], max_length=30, verbose_name='نوع مشاوره'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='date',
            field=models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ مشاوره'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='name_and_family',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی'), ('dne', 'انجام\u200cشده')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='time',
            field=models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان مشاوره'),
        ),
        migrations.AlterField(
            model_name='session',
            name='city',
            field=models.CharField(choices=[('teh', 'تهران'), ('krj', 'کرج')], default='تهران', max_length=30, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer_type',
            field=models.CharField(choices=[('ol', 'مالک / موجر'), ('bt', 'خریدار / مستاجر')], max_length=30, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ برگزاری'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name_and_family',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='session',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی'), ('dne', 'انجام\u200cشده')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان برگزاری'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='city',
            field=models.CharField(choices=[('teh', 'تهران'), ('krj', 'کرج')], default='تهران', max_length=30, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='name_and_family',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('acc', 'تایید شده'), ('can', 'لغو شده'), ('pen', 'در حال بررسی'), ('dne', 'انجام\u200cشده')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان بازدید'),
        ),
    ]
