# Generated by Django 5.0.4 on 2024-09-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_counseling_agent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counseling',
            name='agent_status',
        ),
        migrations.RemoveField(
            model_name='session',
            name='agent_status',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='agent_status',
        ),
    ]
