# Generated by Django 5.0.4 on 2024-09-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_counseling_agent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling',
            name='status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
