# Generated by Django 5.0.4 on 2024-09-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_counseling_status_alter_session_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('can', 'لغو شده'), ('dne', 'انجام\u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
