# Generated by Django 5.0.4 on 2024-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_otp_customusermodel_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/auth_picture/', verbose_name='Authentication Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_card',
            field=models.ImageField(blank=True, null=True, upload_to='profile/bank_card/', verbose_name='Bank Card Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to='profile/national_card/', verbose_name='National Card Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=10, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('r', 'Rejected'), ('w', 'Waiting')], max_length=10, null=True, verbose_name='Authentication Status'),
        ),
    ]
