# Generated by Django 5.0.4 on 2024-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_f_name_profile_l_name_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('a', 'Authenticated'), ('n', 'Not Authenticated'), ('i', 'In Progress')], default='n', max_length=10, null=True, verbose_name='Authentication Status'),
        ),
    ]
