# Generated by Django 5.0.4 on 2024-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_birthday_remove_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('a', 'تایید شده'), ('n', 'تایید نشده'), ('i', 'در حال بررسی')], default='n', max_length=10, null=True, verbose_name='وضعیت احراز هویت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='نشانی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/auth_picture/', verbose_name='تصویر احراز هویت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_card',
            field=models.ImageField(blank=True, null=True, upload_to='profile/bank_card/', verbose_name='تصویر کارت بانکی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='f_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='l_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to='profile/national_card/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'آقا'), ('f', 'خانم')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
