# Generated by Django 5.0.4 on 2024-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customusermodel_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='otp_code',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
