# Generated by Django 5.0.4 on 2024-09-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customusermodel_otp_code'),
        ('restates', '0027_alter_tradesession_status'),
        ('services', '0011_alter_counseling_status_alter_session_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='agent_info',
            field=models.CharField(blank=True, choices=[('cmp', 'Completed'), ('dnt', 'تکمیل نشده'), ('ipr', 'در حال بررسی')], default='dnt', max_length=10, null=True, verbose_name='Complete Information'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_agent',
            field=models.CharField(blank=True, choices=[('is', 'هست'), ('wt', 'در انتظار'), ('nt', "Isn't")], default='nt', max_length=10, null=True, verbose_name='Is Agent?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_sheba',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bank Sheba'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_tendency',
            field=models.CharField(blank=True, choices=[('have', 'Have'), ('dont', 'Have not'), ('seen', 'Have seen')], max_length=10, null=True, verbose_name='Course Tendency'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, choices=[('0', 'No Experience'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('4', '4 years'), ('5-10', '5-10 years'), ('abv10', 'More than 10 years')], max_length=10, null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction_way',
            field=models.CharField(blank=True, choices=[('ins', 'اینستاگرام'), ('y&a', 'Course Videos'), ('ads', 'Advertisements'), ('web', 'Website and Google'), ('frd', 'Friends'), ('oth', 'Others')], max_length=10, null=True, verbose_name='Introduction Way'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images/auth/auth_picture/', verbose_name='تصویر احراز هویت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_card',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images/auth/bank_card/', verbose_name='تصویر کارت بانکی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images/auth/national_card/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=10, null=True, verbose_name='وضعیت پرداخت')),
                ('is_commissioned', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], default='no', max_length=10, null=True, verbose_name='Commission Status')),
                ('is_requested', models.CharField(blank=True, choices=[('tkn', 'Taken'), ('fre', 'Free'), ('pen', 'در حال بررسی')], default='fre', max_length=10, null=True, verbose_name='Request Status')),
                ('unique_url_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('cns', 'مشاوره'), ('ses', 'نشست'), ('vis', 'بازدید'), ('tds', 'Trade Session')], max_length=6, null=True, verbose_name='Task Type')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_session_agent', to=settings.AUTH_USER_MODEL)),
                ('task_counseling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_task', to='services.counseling')),
                ('task_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_task', to='services.session')),
                ('task_trade_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_session_task', to='restates.tradesession')),
                ('task_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_task', to='services.visit')),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
    ]
