# Generated by Django 5.0.4 on 2024-05-06 17:35

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='blogs/', verbose_name='Blog cover')),
                ('title', models.CharField(max_length=200, verbose_name='Blog title')),
                ('body', django_quill.fields.QuillField(verbose_name='Blog body')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Datetime of creation')),
                ('date_modification', models.DateField(auto_now=True, verbose_name='Datetime of modification')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], max_length=3, verbose_name='Blog status')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='blog.blogcategory', verbose_name='Blog category')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
    ]
