# Generated by Django 5.0.4 on 2024-04-29 13:26

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='blogs/', verbose_name='Blog cover')),
                ('title', models.CharField(max_length=200, verbose_name='Blog title')),
                ('body', tinymce.models.HTMLField(verbose_name='Blog body')),
                ('date_time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
                ('date_time_modification', models.DateTimeField(auto_now=True, verbose_name='Datetime of modification')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], max_length=3, verbose_name='Blog status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Blog author')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory', verbose_name='Blog category')),
            ],
            options={
                'ordering': ('-date_time_modification',),
            },
        ),
    ]
