# Generated by Django 5.0.4 on 2024-05-01 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_creation',)},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_time_creation',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_time_modification',
        ),
        migrations.AddField(
            model_name='blog',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datetime of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='date_modification',
            field=models.DateField(auto_now=True, verbose_name='Datetime of modification'),
        ),
    ]
