# Generated by Django 5.0.4 on 2024-05-28 11:03

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'تایید شده'), ('rej', 'Rejected'), ('wit', 'Waiting')], default='wit', max_length=30, null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.CharField(blank=True, choices=[('acc', 'تایید شده'), ('rej', 'Rejected'), ('wit', 'Waiting')], default='wit', max_length=30, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='blog.blogcategory', verbose_name='دسته\u200cبندی بلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_quill.fields.QuillField(verbose_name='متن بلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(upload_to='blogs/', verbose_name='تصویر بلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_modification',
            field=models.DateField(auto_now=True, verbose_name='تاریخ اصلاح'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], max_length=3, verbose_name='وضعیت بلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان بلاگ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=500, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.CharField(max_length=500, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_pr', to='blog.reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
    ]
