# Generated by Django 5.0.4 on 2024-05-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='book',
            new_name='blog',
        ),
    ]
