# Generated by Django 5.0.4 on 2024-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_status_reply_status_alter_blog_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(upload_to='blogs/covers/', verbose_name='تصویر بلاگ'),
        ),
    ]
