# Generated by Django 5.0.4 on 2024-05-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_remove_blog_date_time_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='blog.blogcategory', verbose_name='Blog category'),
        ),
    ]
