# Generated by Django 5.0.4 on 2024-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogcomment_recommend_remove_blogcomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_active',
            field=models.BooleanField(choices=[('Proved', 'Proved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
