# Generated by Django 5.0.4 on 2024-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_active',
            field=models.BooleanField(choices=[('pr', 'Proved'), ('pd', 'Pending'), ('rj', 'Rejected')]),
        ),
    ]
