# Generated by Django 5.0.4 on 2024-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcomment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_active',
            field=models.CharField(choices=[('pr', 'Proved'), ('pd', 'Pending'), ('rj', 'Rejected')], default='pd', max_length=15),
        ),
    ]
