# Generated by Django 5.0.4 on 2024-05-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcomment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent_comment',
        ),
    ]
