# Generated by Django 5.0.4 on 2024-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=230, verbose_name='File Title'),
        ),
    ]
